### ISSUE TITLE
Doesn't work on iOS...

### ISSUE THREAD

**Issue by ManuTeMaia** [rnicholus/frame-grab.js#18]
I use frame-grab.js with dropzone.js. Here is the code:

`mmdDz.on("addedfile", function(file) {
    var comps = file.name.split(".");
    if (comps.length === 1 || (comps[0] === "" && comps.length === 2)) {
        return;
    }
    var ext = comps.pop().toLowerCase(); 
   if (ext == 'mov' || ext == 'mpeg' || ext == 'mp4' || ext == 'wmv') {
   console.log("extention: " + ext);
       FrameGrab.blob_to_video(file).then(
            function videoRendered(videoEl) {
                var frameGrab = new FrameGrab({video: videoEl});
                var imgEl = file.previewElement.querySelector("img");
                console.log("img: " + imgEl + " /// videoEl: " + videoEl);
                frameGrab.grab(imgEl, 1, 220).then(
                    function frameGrabbed(itemEntry) {
                     console.log("file: " + itemEntry);
                        self.emit('thumbnail', file, itemEntry.container.src);
                    },
                    function frameFailedToGrab(reason) {
                        console.log("Can't grab the video frame from file: " +
                            file.name + ". Reason: " + reason);
                    }
                );
            },
            function videoFailedToRender(reason) {
                console.log("Can't convert the file to a video element: " +
                    file.name + ". Reason: " + reason);
            }
        );
    }
});`
It works fine on desktop & safari mobile emulator but it doesn't on iphone or ipad. I can't catch why... No errors in console log 
`console.log("extention: " + ext) `- returns right extention
`console.log("img: " + imgEl + " /// videoEl: " + videoEl);` - returns nothing

**Comment by rnicholus** [comment]
Log statements never return a value. You haven't provided any useful details here so I can't help further, but if you spend a little time debugging, you will be able to determine where the issue lies

**Comment by rnicholus** [comment]
Also, please learn how to format code. Your question is unreadable as a result

**Comment by rnicholus** [comment]
no issue here
